function ReportHeader() {

    const date = new Date().toLocaleString();

    return (

        <div className="mb-8 border-b border-slate-700 pb-6">

            <h1 className="text-4xl font-bold">

                Software Requirements Specification

            </h1>

            <p className="mt-3 text-slate-400">

                Generated by ClarifAI

            </p>

            <p className="text-sm text-slate-500">

                {date}

            </p>

        </div>

    );

}

export default ReportHeader;