function ReportHeader({ project, createdAt }) {
  const formattedDate = createdAt
    ? new Date(createdAt).toLocaleString()
    : new Date().toLocaleString();

  return (
    <div className="mb-8 border-b border-slate-700 pb-6">

      <h1 className="text-4xl font-bold">
        Software Requirements Specification
      </h1>

      <p className="mt-3 text-slate-400">
        Generated by ClarifAI
      </p>

      {project && (
        <p className="mt-2 text-sm text-slate-300">
          Project:{" "}
          <span className="text-indigo-400">
            {project}
          </span>
        </p>
      )}

      <p className="text-sm text-slate-500">
        {formattedDate}
      </p>

    </div>
  );
}

export default ReportHeader;